### ISSUE TITLE
Are proxy commits still blocked for non-committers

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/git-eca-rest-api#56]
Coming from the Gerrit validation logic, we have logic in the ECA service that checks whether the committer is the same as the author. If they are different and the project is tracked (like within PMI), the committer needs to be a committer on the project, otherwise the commit is rejected. 

@chrisguindon had told me that this is no longer a requirement and is not a legal issue. I wanted to check in whether these proxy commits still need to be checked, or if we only care about the authors.

//cc @waynebeaton

**Comment by chrisguindon** [comment]
Additional Context:

I believe this was put in place to restrict non-committers from creating Gerrit patches on behalf of another user. For example, as a committer on the dash-project, I am allowed to push a Gerrit patch made by my colleague Shanda.

..but since Shanda is not a committer on the project, she is NOT allowed to submit a Gerrit patch on behalf of another co-worker. 

She can only push a commit where she is the author and the committer.

**Comment by chrisguindon** [comment]
@waynebeaton can we safely assume that the only check we need to do now is to make sure that the user listed in the author filed has a valid ECA on file.

**Comment by waynebeaton** [comment]
What are the actual scenarios that we need to address?

Semantically, the committer is the entity that actually puts the commit together. Theoretically, somebody could take somebody else's content and assemble a commit from it, but that's more of an IP due diligence problem that I think we need to rely on the committers to identify.

IMO, we should check that **both** the committer and the author have signed the ECA and the committer must be the one submitting the PR.

Does this make sense?

**Comment by chrisguindon** [comment]
> IMO, we should check that both the committer and the author have signed the ECA and the committer must be the one submitting the PR.

The issue is that we are hoping to resolve is that sometimes the committer is Github <noreply@github.com> when the commit is done via Github WebUI. 

Example:
https://api.github.com/repos/eclipsefdn-webdev/Test-Access-Repo/pulls/3/commits

```
"author": {
"name": "Martin Lowe",
"email": "mtl....@....ca",
"date": "2021-03-16T17:28:23Z"
},
"committer": {
"name": "GitHub",
"email": "noreply@github.com",
"date": "2021-03-16T17:28:23Z"
},
```

We never validated the committer field on Github. Instead, we validate the author of each commit but we are currently in process of migrating the validation logic for Github ECA to use this API service.

The question that I have are:

1) Should we start validating the committer on Github
2) If so, should we "whitelist" noreply@github.com for all projects since I doubt they will ever sign an ECA.

I am being cautious here since I don't want to add more friction to the contribution process.

**Comment by waynebeaton** [comment]
> 1. Should we start validating the committer on Github

Yes.

> 2. If so, should we "whitelist" [noreply@github.com](mailto:noreply@github.com) for all projects since I doubt they will ever sign an ECA.

Yes.

**Comment by chrisguindon** [comment]
Thanks @waynebeaton 

@autumnfound It looks like we have the info that we need. How much work is it for you to whitelist commits from noreply@github.com?

**Comment by autumnfound** [comment]
Very little! We can just add a property in our application config, and add a little skip condition in validation
